# Generated by Django 3.1.1 on 2020-09-23 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome do Mapa')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('sistema_origem', models.CharField(max_length=30, verbose_name='Sistema Origem')),
                ('sistema_destino', models.CharField(max_length=30, verbose_name='Sistema Destino')),
            ],
            options={
                'verbose_name_plural': 'mapas',
                'db_table': 'mapa',
            },
        ),
        migrations.CreateModel(
            name='MapaCampos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela_o', models.CharField(max_length=30, verbose_name='Tabela Origem')),
                ('campo_o', models.CharField(max_length=40, verbose_name='Campo Origem')),
                ('campo_o_tipo', models.CharField(choices=[('C', 'Caractere'), ('N', 'Numerico'), ('D', 'Data'), ('H', 'Hora'), ('DT', 'Data e Hora'), ('B', 'Boleano'), ('I', 'Imagem'), ('T', 'Texto')], default='C', max_length=2, verbose_name='Tipo de dados')),
                ('campo_o_tam', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('campo_o_dec', models.CharField(blank=True, max_length=2, null=True, verbose_name='Decimais')),
                ('campo_o_validos', models.TextField(verbose_name='Valores Válidos')),
                ('campo_o_formato', models.TextField(verbose_name='Formato')),
                ('tabela_d', models.CharField(max_length=30, verbose_name='Tabela Destino')),
                ('campo_d', models.CharField(max_length=40, verbose_name='Campo Destino')),
                ('campo_d_tipo', models.CharField(choices=[('C', 'Caractere'), ('N', 'Numerico'), ('D', 'Data'), ('H', 'Hora'), ('DT', 'Data e Hora'), ('B', 'Boleano'), ('I', 'Imagem'), ('T', 'Texto')], default='C', max_length=2, verbose_name='Tipo de dados')),
                ('campo_d_tam', models.CharField(max_length=10, verbose_name='Tamanho')),
                ('campo_d_dec', models.CharField(blank=True, max_length=2, null=True, verbose_name='Decimais')),
                ('campo_d_validos', models.TextField(verbose_name='Valores Válidos')),
                ('campo_d_formato', models.TextField(verbose_name='Formato')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mapa')),
            ],
            options={
                'verbose_name_plural': 'mapcampos',
                'db_table': 'mapacampo',
            },
        ),
        migrations.AddIndex(
            model_name='mapa',
            index=models.Index(fields=['nome'], name='mapa_name_idx'),
        ),
        migrations.AddIndex(
            model_name='mapacampos',
            index=models.Index(fields=['tabela_o', 'campo_o'], name='mapa_campo_idx'),
        ),
    ]
