# Generated by Django 3.1.1 on 2020-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapacampos',
            name='regra_conversao',
            field=models.TextField(blank=True, null=True, verbose_name='Regra de Conversão'),
        ),
    ]
