# Generated by Django 3.1.1 on 2020-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201001_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Projeto'),
        ),
    ]
