# Generated by Django 3.1.1 on 2020-10-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201002_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='trocar_senha',
            field=models.BooleanField(default=True, max_length=1, verbose_name='Trocar Senha?'),
        ),
    ]
